controllers/album.py
from flask import *
from .db import get_db
import hashlib
import time
import os

album = Blueprint('album', __name__, template_folder='templates')

@album.route('/album/edit', methods=['GET', 'POST'])
def album_edit_route():
	error_info = ""
	albumid = request.args.get('id')
	if not check_album_id(albumid):
		abort(404)

	if request.method == "POST":
		operation = request.form["op"]
		if operation == "delete":
			picid = request.form["picid"]
			if check_pic_exist(albumid, picid):
				delete_pic(picid)
		elif operation == "add":
			file = request.files['file']
			if file and check_img_ext(file.filename):
				picid = get_hash(albumid, file.filename)
				if check_pic_exist(albumid, picid):  # if picid haven't been added
					error_info = "Failed! Photo already exists in this album! Please choose another photo"
				else:	
					format = file.filename[-3:]
					date = time.strftime('%Y-%m-%d')
					add_pic(picid, format, date, albumid)
					if not os.path.exists("static/images"):
						os.mkdir("static/images")
					file.save(os.path.join("static", "images", picid+"."+format))
				
	options = {"edit": True, "error_info": error_info, "albumid": albumid, "pics": get_pics(albumid)}
	return render_template("album.html", **options)

@album.route('/album')
def album_route():
	albumid = request.args.get('id')
	if not check_album_id(albumid):
		abort(404)

	options = {"edit": False, "pics": get_pics(albumid), "albumid": albumid}
	return render_template("album.html", **options)


def delete_pic(picid):
	db = get_db()
	cur = db.cursor()
	cur.execute("SELECT format FROM Photo WHERE picid=%s", [picid])
	results = cur.fetchall()
	format = results[0][0]
	cur.execute("DELETE FROM Contain WHERE picid=%s", [picid])
	cur.execute("DELETE FROM Photo WHERE picid=%s", [picid])
	db.commit()

	filename = os.path.join("static", "images", picid+"."+format)
	if os.path.exists(filename):
		os.remove(filename)

def add_pic(picid, format, date, albumid):
	db = get_db()
	cur = db.cursor()
	cur.execute("SELECT MAX(sequencenum) FROM Contain WHERE albumid=%s", [albumid])
	results = cur.fetchall()
	if not results[0][0] == None:
		sequencenum = results[0][0]
	else:
		sequencenum = -1

	cur = db.cursor()
	cur.execute("INSERT INTO Photo (picid, format, date) VALUES (%s, %s, %s)", (picid, format, date))
	cur.execute("INSERT INTO Contain (albumid, picid, caption, sequencenum) VALUES (%s, %s, %s, %s)", (albumid, picid, "", sequencenum+1))
	cur.execute("COMMIT")
	db.commit()



def get_pics(albumid):
	db = get_db()
	cur = db.cursor()
	cur.execute("SELECT picid FROM Contain WHERE albumid=%s ORDER BY sequencenum", [albumid])
	results = cur.fetchall()

	pics = []
	for res in results:
		db = get_db()
		cur2 = db.cursor()
		cur2.execute("SELECT format FROM Photo WHERE picid=%s", [res[0]])
		results2 = cur2.fetchall()
		pics.append(res[0]+'.'+results2[0][0])
	return pics

def check_pic_exist(albumid, picid):
	db = get_db()
	cur = db.cursor()
	cur.execute("SELECT picid FROM Contain WHERE albumid=%s", [albumid])
	results = cur.fetchall()

	for res in results:
		if picid == res[0]:
			return True
	return False


def check_img_ext(filename):
	fname, fileext = os.path.splitext(filename)
	fileext = fileext[1:].lower()
	if fileext == "png" or fileext == "jpg" or fileext == "bmp" or fileext == "bmp":
		return True
	return False

def check_album_id(albumid):
	db = get_db()
	cur = db.cursor()
	cur.execute("SELECT albumid FROM Album WHERE albumid=%s", [albumid])
	results = cur.fetchall()
	if results:
		return True
	return False


def get_hash(albumid, filename):
	db = get_db()
	cur = db.cursor()
	cur.execute("SELECT username, title FROM Album WHERE albumid=%s", [albumid])
	results = cur.fetchall()

	username, album_title = results[0]
	username_enc = username.encode('utf-8')
	album_title_enc = album_title.encode('utf-8')
	filename_enc = filename.encode('utf-8')
	m = hashlib.md5(username_enc + album_title_enc + filename_enc)
	return m.hexdigest()

controllers/albums.py
from flask import *
from .db import get_db
import os

albums = Blueprint('albums', __name__, template_folder='templates')

@albums.route('/albums/edit', methods=['GET', 'POST'])
def albums_edit_route():
	# with open(os.path.join('static', 'log.log'), "a") as logfile:
	# 	log = time.strftime('%Y-%m-%d %H:%M:%S') + " "
	# 	if request.method == "POST":
	# 		log += "POST"
	# 	else:
	# 		log += "GET"
	# 	log += " " + request.url
	# 	if request.method == "POST":
	# 		log += " ("
	# 		for key in request.form.keys():
	# 			log += key + ":" + request.form[key] + ","
	# 		log += ")"
	# 	logfile.write(log+"\n")

	error_info = ""
	if request.method == "POST":
		if not ("op" in request.form.keys()):
			abort(404)
		operation = request.form["op"]
		if operation == "delete":
			albumid = request.form["albumid"]
			if not ("albumid" in request.form.keys()):
				abort(404)
			if not check_album_id(albumid):
				abort(404)
			delete_album(albumid)
		elif operation == "add":
			username = request.form["username"]
			if not ("username" in request.form.keys()):
				abort(404)
			if not check_user_name(username):
				abort(404)
			if not ("title" in request.form.keys()):
				abort(404)
			album_title = request.form["title"]
			if check_album_exist(album_title):
				error_info = "Failed! Album title already exists! Please choose another title"
			else:
				add_album(username, album_title)
		else:
			abort(404)

	user_albums, username = get_user_albums()

	options = {
		"edit": True,
		"error_info": error_info,
		"username": username,
		"user_albums": user_albums
	}
	return render_template("albums.html", **options)


@albums.route('/albums')
def albums_route():
	# with open(os.path.join('static', 'log.log'), "a") as logfile:
	# 	log = time.strftime('%Y-%m-%d %H:%M:%S') + " "
	# 	if request.method == "POST":
	# 		log += "POST"
	# 	else:
	# 		log += "GET"
	# 	log += " " + request.url
	# 	if request.method == "POST":
	# 		log += " ("
	# 		for key in request.form.keys():
	# 			log += key + ":" + request.form[key] + ","
	# 		log += ")"
	# 	logfile.write(log+"\n")

	user_albums, username = get_user_albums()

	options = {
		"edit": False,
		"username": username,
		"user_albums": user_albums
	}
	return render_template("albums.html", **options)

def check_user_name(username):
	db = get_db()
	cur = db.cursor()
	cur.execute("SELECT username FROM User WHERE username=%s", [username])
	results = cur.fetchall()
	if not results:
		return False
	return True

def check_album_id(albumid):
	db = get_db()
	cur = db.cursor()
	cur.execute("SELECT albumid FROM Album WHERE albumid=%s", [albumid])
	results = cur.fetchall()
	if not results:
		return False
	return True

''' Utility functions to query database and get results '''
def get_user_albums():
	db = get_db()
	cur = db.cursor()
	username = request.args.get('username') # Get username from template file albums.html

	if not check_user_name(username):
		abort(404)

	albums = []
	cur.execute("SELECT albumid, title FROM Album WHERE username=%s", [username])
	results = cur.fetchall()
	for res in results:
		albums.append(res)

	return albums, username	

def delete_album(albumid):
	db = get_db()
	cur = db.cursor()

	#Find if there is photo in the album and delete from filesystem
	cur.execute("SELECT picid, format FROM Photo WHERE picid IN (SELECT picid FROM Contain WHERE albumid=%s)", [albumid])
	picid_results = cur.fetchall()
	if picid_results:
		for res in picid_results:
			photo_path = os.path.join("static", "images", res[0]+"."+res[1])
			if os.path.exists(photo_path):
				os.remove(photo_path)

	cur.execute("DELETE FROM Album WHERE albumid=%s", [albumid])
	db.commit()


def add_album(username, album_title):
	db = get_db()
	cur = db.cursor()
	cur.execute("INSERT INTO\
				Album(albumid, title, created, lastupdated, username)\
	 			VALUES\
	 			(NULL, %s, NULL, NULL, %s)", [album_title, username])
	db.commit()

def check_album_exist(album_title):
	user_albums, username = get_user_albums()
	for album_info in user_albums:
		if album_title == album_info[1]:
			return True
	return False

controllers/main.py
from flask import *
from .db import get_db

main = Blueprint('main', __name__, template_folder='templates')


@main.route('/')
def main_route():
	db = get_db()
	cur = db.cursor()

	query = "SELECT username FROM User"
	cur.execute(query)
	results = cur.fetchall() #results will be a tuple of tuples
	
	usernames = []
	for ele in results:
		usernames.append(ele[0])

	options = {
		"usernames": usernames
	}
	return render_template("index.html", **options)

controllers/pic.py
from flask import *
from .db import get_db

pic = Blueprint('pic', __name__, template_folder='templates')


@pic.route('/pic')
def pic_route():
	db = get_db()
	cur = db.cursor()
	picid = request.args.get('id')
	if not check_pic_id(picid):
		abort(404)

	cur.execute("SELECT format FROM Photo WHERE picid=%s", [picid])
	results = cur.fetchall()
	format = results[0][0]

	cur = db.cursor()
	cur.execute("SELECT albumid FROM Contain WHERE picid=%s", [picid])
	results = cur.fetchall()
	albumid = results[0][0]

	cur = db.cursor()
	cur.execute("SELECT sequencenum FROM Contain WHERE picid=%s", [picid])
	results = cur.fetchall()
	sequencenum = results[0][0]

	if sequencenum > 0:
		cur = db.cursor()
		cur.execute("SELECT picid FROM Contain WHERE albumid=%s AND sequencenum=%s", (albumid, sequencenum-1))
		results = cur.fetchall()
		prev_picid = results[0][0]
	else:
		prev_picid = ""

	cur = db.cursor()
	cur.execute("SELECT picid FROM Contain WHERE albumid=%s AND sequencenum=%s", (albumid, sequencenum+1))
	results = cur.fetchall()
	if results:
		next_picid = results[0][0]
	else:
		next_picid = ""

	options = {
		"picid": picid,
		"format": format,
		"prev_picid": prev_picid,
		"next_picid": next_picid,
		"albumid": albumid
	}

	return render_template("pic.html", **options)


def check_pic_id(picid):
	db = get_db()
	cur = db.cursor()
	cur.execute("SELECT picid FROM Photo WHERE picid=%s", [picid])
	results = cur.fetchall()
	if results:
		return True
	return False

templates/album.html
{% extends "base.html" %}

{% block content %}
    <header><a href="{{ url_for('main.main_route') }}">Photo Albums Collection</a></header>
    <h1>ALBUM</h1>

    <div class="information-content">
    {% if pics %}
        <table align="center">
        {% for pic in pics %}
            {% set photo_id = pic[:-4] %}
              {% set pic_link_id = "pic_" + photo_id|string() + "_link" %}
            <tr>
            <td>
                <a id="{{ pic_link_id }}" href="{{ url_for('pic.pic_route', id=photo_id) }}"><img src="{{ url_for('static', filename='images/'+pic) }}" width="300px" /></a>
            </td>

            {% if edit %}
              {% set delete_pic_id = "delete_pic_" + photo_id|string() %}
                <td>
                    <form action="" method="POST">
                      <input type="hidden" name="op" value="delete">
                      <input type="hidden" name="albumid" value="{{ albumid }}">
                      <input type="hidden" name="picid" value="{{ photo_id }}">
                      <button  id="{{ delete_pic_id }}" class="btn btn-primary" type="submit">Delete</button>
                    </form>
                </td>
            {% endif %}
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <p>Oops...There is no photo for this album!</p>
    {% endif %}
  </div>

    {% if error_info %}
        <div class="alert alert-success">
          <a href="#" class="close" data-dismiss="alert" aria-label="Close">&times;</a>
          <p>{{ error_info }}</p>
        </div>
    {% endif %}


    {% if edit %}
      <div class="edit-component">
        {% include 'snippets/add_new_photo.html' %}
      </div>
    {% else %}
        <a href="{{ url_for('album.album_edit_route', id=albumid ) }}">
            <button class="btn btn-primary btn-lg">Edit Album</button>
        </a>
    {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="description" content="IFotos">
	<meta name="author" content="Wei Xu, Changhan Wang, Zhuo Chen"> 
	
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">


    <link rel="stylesheet" href="/static/css/style.css" />
	<link rel="icon" href="/static/css/favicon.png">
    <title>IFotos</title>
    
</head>
<body>
  <img class="homepage-background"  src="/static/css/background.jpg">
  <div class="center">
    {% block content %}{% endblock %}
  </div>

  <script type="text/javascript" src="/static/js/main.js"></script>

</body>

</html>

templates/index.html
{% extends "base.html" %}


{% block content %}
	<div>
    	<header>Photo Albums Collection</header>	    
		<div class="username" >
		    <h1>USERS</h1>
		    <div "information-content">
			    <table align="center">	
				    {% if usernames %}
				    	{% for username in usernames %}
				   		{% set user_albums_id = "user_albums_" + username %}
				    	<tr>
				    		<td class="avatar"><span>{{ username[0].upper() }}</span></td>
				    		<td>{{ username }}</td>
			    			<td><a id="{{ user_albums_id }}" href="{{ url_for('albums.albums_route', username=username) }}"><button class="btn btn-primary">View Albums</button></a> </td>
			    			</td>
			    		</tr>
				    	{% endfor %}
				    {% endif %}
				</table>
			</div>
		</div>

	    <footer>
			<p>Designed by Wei Xu, Changhan Wang, and Zhuo Chen</p>
			<p>Updated by Israel Ike Friedman for Python3 and MySQL 8.4</p>
		</footer>
	</div>

{% endblock %}